---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: kb
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "kb1110/scientific_calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Stop and remove existing container if present and running
      shell: docker stop scientific_calculator && docker rm scientific_calculator
      ignore_errors: true
        
    - name: Start Docker service
      service:
        name: docker
        state: started
        
    - name: Running container
      shell: docker run -it --name scientific_calculator kb1110/scientific_calculator
