---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: kb
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "kb1110/scientific_calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -d --name scientific_calculator -v $PWD:/app kb1110/scientific_calculator

    - name: Execute Java application inside container
      shell: docker exec -it scientific_calculator java -jar demo.jar
